# Generated by Django 6.0.4 on 2026-04-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ai_reponse',
            new_name='Ai_Response',
        ),
    ]
