# Generated by Django 6.0.4 on 2026-04-12 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_ai_reponse_ai_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ai_response',
            name='user_query',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.user_input'),
        ),
    ]
